/**
 * Prestito
 * Prestito
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { FileDto } from '../model/models';

import { Configuration } from '../configuration';

export interface FileServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   * return all files
   */
  getFiles(extraHttpRequestParams?: any): Observable<Array<FileDto>>;
}
